<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="OIT-CT1ALTMARIF" name="com.eisrem.testCases.Release2022.TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg" tests="1" failures="1" timestamp="2022-04-29T11:43:07 EDT" time="89.066" errors="0">
  <testcase name="TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg_001" time="89.066" classname="com.eisrem.testCases.Release2022.TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg">
    <failure type="java.lang.AssertionError" message="Test Failed. Error occured while trying to complete all steps:  expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed. Error occured while trying to complete all steps:  expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.eisrem.AppUtils.SeleniumHelper.assertFail(SeleniumHelper.java:1958)
at com.eisrem.testCases.Release2022.TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg.TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg_001(TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg_001 -->
  <system-out/>
</testsuite> <!-- com.eisrem.testCases.Release2022.TC_BHOPS_11627_Location_Identifier_Start_Date_Error_Msg -->
